services:
  user:
    build: ./user
    image: manohari07/user:1.0.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    build: ./cart
    image: manohari07/cart:1.0.0
    container_name: cart
    depends_on:
      - redis
      - catalogue


  catalogue:
    build: ./catalogue
    image: manohari07/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb

  shipping:
    build: ./shipping
    image: manohari07/shipping:1.0.0
    container_name: shipping
    depends_on:
      - mysql
      - cart
 
  mongodb:
    build: ./mongodb # it moves to mongodb directory
    image: manohari07/mongodb:1.0.0 # docker build -t joindevops/mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

  mysql:
    build: ./mysql # it moves to mongodb directory
    image: manohari07/mysql:1.0.0 # docker build -t joindevops/mongodb:1.0.0
    container_name: mysql

  frontend:
    build: ./frontend
    image: manohari07/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart

  

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # if true, you need to create network manually


